-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 09:13:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NULL,
  `email_usuario` VARCHAR(100) NULL,
  `senha_usuario` VARCHAR(255) NULL,
  `data_criação_usuario` DATE NULL,
  `bio_usuario` VARCHAR(150) NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`Usuario_id`),
  INDEX `fk_Usuario_tipo_usuario_idx` (`tipo_usuario_id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacao` (
  `id_publicacao` INT NOT NULL AUTO_INCREMENT,
  `conteudo` LONGTEXT NOT NULL,
  `data_publicacao` DATE NOT NULL,
  `Usuario_Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_publicacao`),
  INDEX `fk_publicacao_Usuario1_idx` (`Usuario_Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicacao_Usuario1`
    FOREIGN KEY (`Usuario_Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curtida` (
  `curtida_id` INT NOT NULL AUTO_INCREMENT,
  `data_curtida` DATE NOT NULL,
  `publicacao_id_publicacao` INT NOT NULL,
  `Usuario_Usuario_id` INT NOT NULL,
  PRIMARY KEY (`curtida_id`),
  INDEX `fk_curtida_publicacao1_idx` (`publicacao_id_publicacao` ASC) VISIBLE,
  INDEX `fk_curtida_Usuario1_idx` (`Usuario_Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_curtida_publicacao1`
    FOREIGN KEY (`publicacao_id_publicacao`)
    REFERENCES `mydb`.`publicacao` (`id_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curtida_Usuario1`
    FOREIGN KEY (`Usuario_Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`midia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`midia` (
  `midia_id` INT NOT NULL AUTO_INCREMENT,
  `caminho_arquivo` VARCHAR(1000) NOT NULL,
  `nome_arquivo` VARCHAR(1000) NOT NULL,
  `data_publicacao` DATE NOT NULL,
  `tamanho_arquivo` INT NOT NULL,
  `data_upload` DATE NOT NULL,
  `tipo_midia` VARCHAR(45) NOT NULL,
  `publicacao_id_publicacao` INT NOT NULL,
  PRIMARY KEY (`midia_id`),
  INDEX `fk_midia_publicacao1_idx` (`publicacao_id_publicacao` ASC) VISIBLE,
  CONSTRAINT `fk_midia_publicacao1`
    FOREIGN KEY (`publicacao_id_publicacao`)
    REFERENCES `mydb`.`publicacao` (`id_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questionario` (
  `id_questionario` INT NOT NULL AUTO_INCREMENT,
  `nome_questionario` VARCHAR(45) NOT NULL,
  `perfil_definido` VARCHAR(45) NOT NULL,
  `Usuario_Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_questionario`),
  INDEX `fk_questionario_Usuario1_idx` (`Usuario_Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_questionario_Usuario1`
    FOREIGN KEY (`Usuario_Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pergunta` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT,
  `descricao_pergunta` LONGTEXT NOT NULL,
  `questionario_id_questionario` INT NOT NULL,
  PRIMARY KEY (`id_pergunta`),
  INDEX `fk_pergunta_questionario1_idx` (`questionario_id_questionario` ASC) VISIBLE,
  CONSTRAINT `fk_pergunta_questionario1`
    FOREIGN KEY (`questionario_id_questionario`)
    REFERENCES `mydb`.`questionario` (`id_questionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respostas` (
  `id_respostas` INT NOT NULL AUTO_INCREMENT,
  `descricao_resposta` LONGTEXT NOT NULL,
  `pergunta_id_pergunta` INT NOT NULL,
  PRIMARY KEY (`id_respostas`),
  INDEX `fk_respostas_pergunta1_idx` (`pergunta_id_pergunta` ASC) VISIBLE,
  CONSTRAINT `fk_respostas_pergunta1`
    FOREIGN KEY (`pergunta_id_pergunta`)
    REFERENCES `mydb`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarefa` (
  `id_tarefa` INT NOT NULL AUTO_INCREMENT,
  `nome_tarefa` VARCHAR(45) NOT NULL,
  `descricao_tarefa` MEDIUMTEXT NOT NULL,
  `data_hora_inicio` DATETIME NOT NULL,
  `data_hora_fim` DATETIME NOT NULL,
  `prioridade_tarefa` VARCHAR(45) NOT NULL,
  `Usuario_Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_tarefa`),
  INDEX `fk_tarefa_Usuario1_idx` (`Usuario_Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarefa_Usuario1`
    FOREIGN KEY (`Usuario_Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`Usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
